repo: 'modular-nav'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - gridifier
  - typografier
  - css-order-grid-type-main
  - responsive-css
  - body-margin-0
  - border-box
  - screenshots-all
  - nav-hover

html:
  - path: 'index.html'
    has:
      - 'header'
      - 'header div'
      - 'header h1'
      - 'header nav'
      - 'header nav ul'
      - 'header nav li'
      - 'header nav li a'
    search:
      - 'Solar System'
      - 'Planets'
      - 'Moons'
      - 'Exploration'
      - 'grid-middle'

css:
  - path: 'css/main.css'
    has:
      - ['html', 'font-family', 'sans-serif']
    search:
      - 'a:hover'
      - 'text-align: center;'
      - 'text-align: left;'
      - 'display: inline-block;'
      - 'background-color: #e2e2e2;'
      - 'color: #0074d9;'
      - 'color: #fff;'
      - 'background-color: #0074d9;'
      - 'text-decoration: none;'
